### ISSUE TITLE
Webpack 5 warnings

### ISSUE THREAD

**Issue by ntucker** [ntucker/anansi#52]
- [x] "Chunk.hasEntryModule: Use new ChunkGraph API" - webpack-fix-style-only-entries - https://github.com/fqborges/webpack-fix-style-only-entries/issues/31
- [x] "Compilation.assets will be frozen in future" - html-webpack-plguin: https://github.com/jantimon/html-webpack-plugin/issues/1501
- [x] "\<w\> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Managed item [*redacted*]/anansi/node_modules/@babel/core/node_modules/@babel/template isn't a directory or doesn't contain a package.json"
- [x] "[DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback." https://github.com/webpack/webpack-cli/issues/1918

Dropping webpack 4:
- [x] html-webpack-plugin v5 - drops v4 webpack support
- [x] css-loader v5 - drops webpack 4 support
- [x] terser-webpack-plugin v5 - drops webpack 4 support
